name: do-practice-api
region: nyc
services:
  - name: api
    github:
      repo: Pritiks23/DO_practice
      branch: main
      deploy_on_push: true
    build_command: npm ci && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    health_check:
      http_path: /api/v1/health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: API_VERSION
        value: v1
      - key: API_PREFIX
        value: /api
      - key: LOG_LEVEL
        value: info
      - key: CORS_ORIGIN
        value: "*"
    routes:
      - path: /
